package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.io.File;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;

public class CreateNewGroupTests {
  ChromeDriver wd;
  ChromeOptions options;

  @BeforeMethod

  public void setUp() throws Exception {
    System.setProperty("webdriver.chrome.driver", "C:/tools/chromedriver.exe");
    wd = new ChromeDriver();
    wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
    wd.get("http://localhost/addressbook/");
    login();

  }

  private void login() {
    wd.findElement(By.name("user")).sendKeys("admin");
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).sendKeys("secret");
    wd.findElement(By.xpath("//form[@id=\'LoginForm\']/input[3]")).click();
  }

  public void setDriver() {

  }

  @Test
  public void testCreateNewGroup() {
    gotoGroupPage();
    initGroupCreation();
    fillGroupForm();
    submitGroupCreation();
    returnToGroupPage();
    wd.quit();
  }

  private void returnToGroupPage() {
    wd.findElement(By.linkText("group page")).click();
  }

  private void submitGroupCreation() {
    wd.findElement(By.name("submit")).click();
  }

  private void fillGroupForm() {
    wd.findElement(By.name("group_name")).click();
    wd.findElement(By.name("group_name")).sendKeys("testGroup");
    wd.findElement(By.name("group_header")).click();
    wd.findElement(By.name("group_name")).click();
    wd.findElement(By.name("group_header")).click();
    wd.findElement(By.name("group_header")).sendKeys("testGroup");
    wd.findElement(By.name("group_header")).click();
    wd.findElement(By.name("group_header")).sendKeys("testGroup2");
    wd.findElement(By.name("group_footer")).click();
    wd.findElement(By.name("group_footer")).sendKeys("testGroup3");
  }

  private void initGroupCreation() {
    wd.findElement(By.name("new")).click();
  }

  private void gotoGroupPage() {
    wd.findElement(By.linkText("groups")).click();
  }
}
